### ISSUE TITLE
iouyap SIGSEV when IPv6 localhost hostname present in /etc/hosts

### ISSUE THREAD

**Issue by ovidiucs** [GNS3/iouyap#17]
On Arch Linux iouyap will fail to start any images when you have ipv6 localhost defined in /etc/hosts

`::1		localhost.localdomain	localhost jenkins`

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/mig/GNS3/images/IOU/i86bi_linux_l2-ipbasek9-ms.jan24-2013-team_track.bin'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf73a5749 in inet_pton () from /usr/lib32/libc.so.6
(gdb) bt
#0  0xf73a5749 in inet_pton () from /usr/lib32/libc.so.6
#1  0xf7287f01 in ?? () from /usr/lib32/libnss_files.so.2
#2  0xf72884a1 in _nss_files_gethostbyname3_r () from /usr/lib32/libnss_files.so.2
#3  0xf7288914 in _nss_files_gethostbyname_r () from /usr/lib32/libnss_files.so.2
#4  0xf739a214 in gethostbyname_r@@GLIBC_2.1.2 () from /usr/lib32/libc.so.6
#5  0xf73811a9 in gethostid () from /usr/lib32/libc.so.6
#6  0x08461405 in exit ()
#7  0x00000000 in ?? ()

```
BUGS
       gethostbyname() does not recognize components of a dotted IPv4 address string that are expressed in hexadecimal.

A workaround would be to comment the entry in /etc/hosts

**Comment by grossmj** [comment]
iouyap is going to be replaced by uBridge in 2.0, hopefully uBridge won't have the same issue.
